name: .NET build and deploy app

on:
  push:
    branches: [ main ]
env:
 AZURE_WEBAPP_NAME: globalwalletinvestment
 AZURE_WEBAPP_PACKAGE_PATH: './published'
 NETCORE_VERSION: '3.1.x'
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core ${{ env.NETCORE_VERSION}}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION}}
    
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
          
    - name: Publish
      run: dotnet publish --no-build -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH}}
